### ISSUE TITLE
SSX Free giving selector when player already has it

### ISSUE THREAD

**Issue by Diablodesu** [ServerSelectorX/ServerSelectorX#345] opened 2023-05-17 21:30 UTC
I'm using SSX Free on 1.18.2, it is giving the selector when the player already has one, resulting in a duplicate.
Logs also don't indicate any errors.

https://github.com/ServerSelectorX/ServerSelectorX/assets/90352587/682ff7f1-5aab-4e3e-9519-5856648a336e

**Comment by Derkades** [comment] 2023-05-17 21:36
Is this with the slot number set to automatic/first available?

**Comment by Diablodesu** [comment] 2023-05-17 21:41
> Is this with the slot number set to automatic/first available?

I'm just now noticing it's set to the slot used also by the Nether Star, could this be the issue?

**Comment by Derkades** [comment] 2023-05-18 10:30
When a specific slot number is defined (so a slot number equal to or greater than 0) it replaces the item that's already in the slot using `setItem`. Could it be caused by a different plugin moving the item? I don't understand how this can happen

**Comment by Diablodesu** [comment] 2023-05-24 03:43
The nether star is set by other plugin, my guess is that that plugin is taking priority. I set the compass to a slot that isn't already being used, and that seems to have fixed it.

**Comment by Derkades** [comment] 2023-05-24 09:55
Alright, thanks for reporting back. I will close this issue

**Closed as completed by Derkades** 2023-05-24 09:55 UTC
